version: 2

cli:
  server: https://app.fossa.com
  fetcher: git
  project: https://github.com/MomoLangenstein/grim-reaper.git

analyze:
  modules:
  - name: Cargo.lock
    type: cargo
    target: .
    path: .
